name: Deploy Vercel

on: 
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

jobs:
  test-jest:
    name: tests unit
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run test:unit --if-present
      
  test-cypress:
    name: tests e2e
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run dev
          wait-on: http://localhost:3000

  deploy-production:
    needs: [test-jest, test-cypress]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
