name: Tests E2E

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    name: Tests E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run dev
          wait-on: http://localhost:3000
